#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/ervandew/supertab.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/hallison/vim-rdoc.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/davidoc/taskpaper.vim.git",
  "git://github.com/tmhedberg/matchit.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tomtom/tcomment_vim.git",
  "git://github.com/tsaleh/vim-tmux.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/vim-scripts/Gist.vim.git",
  "git://github.com/jistr/vim-nerdtree-tabs.git",
  "git://github.com/scrooloose/syntastic.git",
  "git://github.com/vim-airline/vim-airline.git",
  "git://github.com/majutsushi/tagbar.git",
  "git://github.com/szw/vim-tags.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/leafgarland/typescript-vim.git",
  "git://github.com/valloric/YouCompleteMe.git",
  "git://github.com/airblade/vim-gitgutter.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/kien/ctrlp.vim.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/ervandew/supertab.git",
  "git://github.com/shougo/unite.vim.git",
  "git://github.com/vim-airline/vim-airline-themes.git",
  "git://github.com/tomasr/molokai.git",
  "git://github.com/flazz/vim-colorschemes.git",
  "git://github.com/vim-scripts/taglist.vim.git",
  "git://github.com/shougo/neocomplete.vim.git",
  "git://github.com/davidhalter/jedi-vim.git",
  "git://github.com/groenewege/vim-less.git",
  "git://github.com/elzr/vim-json.git",
  "git://github.com/othree/html5.vim.git",
  "git://github.com/plasticboy/vim-markdown.git",
  "git://github.com/klen/python-mode.git",
  "git://github.com/hail2u/vim-css3-syntax.git",
  "git://github.com/derekwyatt/vim-scala.git",
  "git://github.com/robertbraeutigam/vim-java-tags.git",
  "git://github.com/burnettk/vim-angular.git",
  "git://github.com/vim-scripts/c.vim.git",
  "git://github.com/vim-scripts/nginx.vim.git",
  "git://github.com/sukima/xmledit.git",
  "git://github.com/nono/jquery.vim.git",
  "git://github.com/vim-scripts/VimClojure.git",
  "git://github.com/fatih/vim-go.git",
  "git://github.com/stanangeloff/php.vim.git",
  "git://github.com/hynek/vim-python-pep8-indent.git",
  "git://github.com/moll/vim-node.git",
  "git://github.com/nanotech/jellybeans.vim.git",
  "git://github.com/Raimondi/delimitMate.git",
  "git://github.com/Quramy/tsuquyomi.git",
  "git://github.com/tpope/vim-sensible.git",
  "git://github.com/Shougo/vimproc.vim.git",
  "git://github.com/.git",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
